
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'OBJETO SUJETO VERBOFUTURO VERBOPASADO VERBOPRESENTEparrafo : frasesfrases : frases oracionfrases : oracionoracion : SUJETO VERBOPRESENTE OBJETOoracion : SUJETO VERBOPASADO OBJETOoracion : SUJETO VERBOFUTURO OBJETO'
    
_lr_action_items = {'SUJETO':([0,2,3,5,9,10,11,],[4,4,-3,-2,-4,-5,-6,]),'$end':([1,2,3,5,9,10,11,],[0,-1,-3,-2,-4,-5,-6,]),'VERBOPRESENTE':([4,],[6,]),'VERBOPASADO':([4,],[7,]),'VERBOFUTURO':([4,],[8,]),'OBJETO':([6,7,8,],[9,10,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'parrafo':([0,],[1,]),'frases':([0,],[2,]),'oracion':([0,2,],[3,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> parrafo","S'",1,None,None,None),
  ('parrafo -> frases','parrafo',1,'p_parrafo','ParserTraductor.py',14),
  ('frases -> frases oracion','frases',2,'p_frases_1','ParserTraductor.py',19),
  ('frases -> oracion','frases',1,'p_frases_2','ParserTraductor.py',25),
  ('oracion -> SUJETO VERBOPRESENTE OBJETO','oracion',3,'p_oracion_presente','ParserTraductor.py',38),
  ('oracion -> SUJETO VERBOPASADO OBJETO','oracion',3,'p_oracion_pasado','ParserTraductor.py',44),
  ('oracion -> SUJETO VERBOFUTURO OBJETO','oracion',3,'p_oracion_futuro','ParserTraductor.py',48),
]
